### ISSUE TITLE
window_infer

### ISSUE THREAD

**Issue by GYDDHPY** [ge-xing/Diff-UNet#1]
Hi, thank you for your contributions.

I'm confused by the `window_infer`, which seems to be a MONAI function and is unable to handel the parameter `pred_type="ddim_sample `.

https://github.com/ge-xing/Diff-UNet/blob/14d55bd06bf59e9f4a06d8d08128d4422ba3b891/train.py#L80-L82

https://github.com/ge-xing/Diff-UNet/blob/14d55bd06bf59e9f4a06d8d08128d4422ba3b891/train.py#L123-L128

**Comment by 920232796** [comment]
The window_infer have a parameter **kwargs, So you can input any variables. The variables will be inputed in the forward function of the model (refer to the forward function of Diffusion Model).

**Comment by 920232796** [comment]
Or you may need to install a new version of monai if you can't run the code successfully.

**Comment by 920232796** [comment]
The window_infer has a parameter **kwargs, So you can input any variables. The variables will be inputed in the forward function of the model (refer to the forward function of Diffusion Model).



> Hi, thank you for your contributions.
> 
> I'm confused by the `window_infer`, which seems to be a MONAI function and is unable to handel the parameter `pred_type="ddim_sample `.
> 
> https://github.com/ge-xing/Diff-UNet/blob/14d55bd06bf59e9f4a06d8d08128d4422ba3b891/train.py#L80-L82
> 
> https://github.com/ge-xing/Diff-UNet/blob/14d55bd06bf59e9f4a06d8d08128d4422ba3b891/train.py#L123-L128

**Comment by GYDDHPY** [comment]
Thank you for your quick reply.

**Comment by jessie-chen99** [comment]
> 

Hi, thanks for your reply. I am confused with the code implementation. I can run your code to get predict results, but I cannot find where you write the _Step-Uncertainty based Fusion_ part.  Did you conduct the _Step-Uncertainty based Fusion_ part in this monai function **SlidingWindowInferer**?

**Comment by jessie-chen99** [comment]
> The window_infer has a parameter **kwargs, So you can input any variables. The variables will be inputed in the forward function of the model (refer to the forward function of Diffusion Model).
> 
> > Hi, thank you for your contributions.
> > I'm confused by the `window_infer`, which seems to be a MONAI function and is unable to handel the parameter `pred_type="ddim_sample `.
> > https://github.com/ge-xing/Diff-UNet/blob/14d55bd06bf59e9f4a06d8d08128d4422ba3b891/train.py#L80-L82
> > 
> > https://github.com/ge-xing/Diff-UNet/blob/14d55bd06bf59e9f4a06d8d08128d4422ba3b891/train.py#L123-L128

Hi, thanks for your reply. I am confused with the code implementation too. I can run your code to get predict results, but I cannot find where you write the Step-Uncertainty based Fusion part. Did you conduct the Step-Uncertainty based Fusion part in this monai function SlidingWindowInferer?
