### ISSUE TITLE
how can i change the input channel from 4 to 1 

### ISSUE THREAD

**Issue by zhao9chen99999** [ge-xing/Diff-UNet#2]
Hello, your work is so great!!
i ve already got the results on brats2020,now iam work on my own datasets,but my dataset only have 1 modality （t1），i want to know where can i change the input channel from 4 to 1 ,and what else do i need to change,thx!!!!

**Comment by 920232796** [comment]
self.embed_model = BasicUNetEncoder(3, 4, 2, [64, 64, 128, 256, 512, 64])

self.model = BasicUNetDe(3, 7, 3, [64, 64, 128, 256, 512, 64], 
                                act = ("LeakyReLU", {"negative_slope": 0.1, "inplace": False}))
                               
The second parameter of the two model is 4 and 7, respectively. If your dataset have 1 modality and 2 segmentation targets, you can modify the two number 4, 7 -> 1, 3. And the third parameter of BasicUNetDe is the number of segmentation targets. For example:

self.embed_model = BasicUNetEncoder(3, 1, 2, [64, 64, 128, 256, 512, 64])

self.model = BasicUNetDe(3, 3, 2, [64, 64, 128, 256, 512, 64], 
                                act = ("LeakyReLU", {"negative_slope": 0.1, "inplace": False}))

**Comment by zhao9chen99999** [comment]
> self.embed_model = BasicUNetEncoder(3, 4, 2, [64, 64, 128, 256, 512, 64])
> 
> self.model = BasicUNetDe(3, 7, 3, [64, 64, 128, 256, 512, 64], act = ("LeakyReLU", {"negative_slope": 0.1, "inplace": False}))
> 
> The second parameter of the two model is 4 and 7, respectively. If your dataset have 1 modality and 2 segmentation targets, you can modify the two number 4, 7 -> 1, 3. And the third parameter of BasicUNetDe is the number of segmentation targets. For example:
> 
> self.embed_model = BasicUNetEncoder(3, 1, 2, [64, 64, 128, 256, 512, 64])
> 
> self.model = BasicUNetDe(3, 3, 2, [64, 64, 128, 256, 512, 64], act = ("LeakyReLU", {"negative_slope": 0.1, "inplace": False}))

thanks for your answer!!
my datasets have 1 modality and 1 segmentation targets(wt),does that means i need to adjust like:
self.embed_model = BasicUNetEncoder(3, 1, 1, [64, 64, 128, 256, 512, 64])

self.model = BasicUNetDe(3, 2, 1, [64, 64, 128, 256, 512, 64],

**Comment by 920232796** [comment]
Yes.

**Comment by WeiliJiang** [comment]
Did you solve this problem?

**Comment by ge-xing** [comment]
You need to modify the dataset related codes to construct the right inputs.
You can print the shape in this section:

`def get_input(self, batch):
        image = batch["image"]
        label = batch["label"]
        print(image.shape)
        print(label.shape)
        label = label.float()
        return image, label `

**Comment by ge-xing** [comment]
You need to modify the dataset related codes to construct the right inputs.
You can print the shape in this section:

<img width="386" alt="image" src="https://user-images.githubusercontent.com/109211094/227150415-dbd09137-a665-4a0f-9327-de770af8d6a7.png">

And 

sample_out = self.sample_diffusion.ddim_sample_loop(self.model, (1, 3, 96, 96, 96), model_kwargs={"image": image, "embeddings": embeddings})
The second parameter is (1, 3, 96, 96, 96), you may need to modify the 3 to 1 if your segmentation target number is 1.

**Comment by WeiliJiang** [comment]
you need to look the code at brats_data_utils_multi_label. as # transforms.ConvertToMultiChannelBasedOnBratsClassesD(keys=["label"]),

**Comment by zhao9chen99999** [comment]
> you need to look the code at brats_data_utils_multi_label. as # transforms.ConvertToMultiChannelBasedOnBratsClassesD(keys=["label"]),

thx for that,i'll have a try!

**Comment by OCEANOUXIN** [comment]
> > you need to look the code at brats_data_utils_multi_label. as # transforms.ConvertToMultiChannelBasedOnBratsClassesD(keys=["label"]),
> 
> thx for that,i'll have a try!

Hi! Do you successfully run the train.py after modify the input channel?

**Comment by 920232796** [comment]
You can see the BTCV dir, which has the single-channel input.

**Comment by OCEANOUXIN** [comment]
> You can see the BTCV dir, which has the single-channel input.

Thanks for your reply.But I think I don't catch your meaning.

**Comment by 920232796** [comment]
https://github.com/ge-xing/Diff-UNet/blob/main/BTCV/train.py

This file contains the example of single-channel input.

**Comment by OCEANOUXIN** [comment]
> https://github.com/ge-xing/Diff-UNet/blob/main/BTCV/train.py
> 
> This file contains the example of single-channel input.

hello, I find it the train results of my own dataset are not good, and the test out is not correct.

**Comment by zhao9chen99999** [comment]
I have already received your e-mail，Thanks a lot！我已收到您发送的邮件，感谢您的来信！

**Comment by OCEANOUXIN** [comment]
> https://github.com/ge-xing/Diff-UNet/blob/main/BTCV/train.py
> 
> This file contains the example of single-channel input.

![image](https://github.com/ge-xing/Diff-UNet/assets/90253968/1bb2be9e-707e-4792-8219-b6a3ebd2c443)
I don't know why the valdation process takes so long...

**Comment by OCEANOUXIN** [comment]
> https://github.com/ge-xing/Diff-UNet/blob/main/BTCV/train.py
> 
> This file contains the example of single-channel input.

I modify this :
![image](https://github.com/ge-xing/Diff-UNet/assets/90253968/db916372-130c-49aa-8cce-3e7905f2db3e)
![image](https://github.com/ge-xing/Diff-UNet/assets/90253968/3f1097bb-6bc1-4707-b82e-c19ab34ceeed)
![image](https://github.com/ge-xing/Diff-UNet/assets/90253968/1d31ad87-35b1-472c-91ff-64d1da988c4c)
![image](https://github.com/ge-xing/Diff-UNet/assets/90253968/96af8780-502f-42d4-ab3a-6d3db41c5756)

the result is not ideal.

**Comment by 920232796** [comment]
You can contact with me on the wechat: 18340097191. Thank you!
