### ISSUE TITLE
Issue with "mpi4py" library

### ISSUE THREAD

**Issue by alqurri77** [ge-xing/Diff-UNet#27]
I had an issue installing "mpi4py", is it possible to avoid using this library or is there an alternative?

Thank!

**Comment by 920232796** [comment]
I don't know the "mpi4py". Can you give me more information about this issue?

**Comment by alqurri77** [comment]
I meant this library "from mpi4py import MPI", I had an issue installing it. But it's okay. I figured out it's not essential to run the code, if distributed is not required.
