### ISSUE TITLE
How is the embed_model trained

### ISSUE THREAD

**Issue by SkeletonOne** [ge-xing/Diff-UNet#4]
Hi,

I notice that the optimizer is defined only for the denoising unet model here https://github.com/ge-xing/Diff-UNet/blob/d954bdced66fd245bb20123bfd053a1ae382ba41/BTCV/train.py#L88, and I cannot find the optimizer for the embed_model (feature encoder in the paper). Does it mean the FE is just randomly initialized and not trained? Or are there something I am missing? Thanks.

**Comment by ge-xing** [comment]
Self.model is the instance of  Diff-Uet, it contains the embed_model.

**Comment by SkeletonOne** [comment]
Got it. Thanks!
