### ISSUE TITLE
Visualize the results 

### ISSUE THREAD

**Issue by qb02su** [ge-xing/Diff-UNet#6]
Thank you a lot for your great work. I'd like to visualize my Brats testing segmentation results, which parts of code should I  modify ?

**Comment by 920232796** [comment]
You can modify the "validation_step"  function to visualize or save the model's prediction results.

**Comment by qb02su** [comment]
Thank you so much.

**Comment by CLKSDF** [comment]
Thank you a lot for your great work.Should I use the SaveImage function in MONAI for visualization, even though it will lose the orientation information?"
