### ISSUE TITLE
Environment file requirement.

### ISSUE THREAD

**Issue by GYDDHPY** [ge-xing/Diff-UNet#9]
Hi. Thank you for your contribution.  
Could you please share the environment file of your experiment? I met several re-implementation errors, which I think may due to different environment and packages.  
Looking forward to your reply.

**Comment by 920232796** [comment]
Could you send me the specific error message?  The repo only need a 'monai' package.

**Comment by GYDDHPY** [comment]
> Could you send me the specific error message? The repo only need a 'monai' package.

Thank you for your rapid reply. It seems my torch version lead to such error. I can run the program after I change it.
